const key = Symbol.for("@openDAW/lib-dsp")

if ((globalThis as any)[key]) {
    console.debug(`%c${key.description}%c is already available in ${globalThis.constructor.name}.`, "color: hsl(10, 83%, 60%)", "color: inherit")
} else {
    (globalThis as any)[key] = true
    console.debug(`%c${key.description}%c is now available in ${globalThis.constructor.name}.`, "color: hsl(200, 83%, 60%)", "color: inherit")
}

export * from "./AudioAnalyser"
export * from "./AudioBuffer"
export * from "./adsr"
export * from "./audio-data"
export * from "./bpm-tools"
export * from "./biquad-coeff"
export * from "./biquad-processor"
export * from "./crusher"
export * from "./chords"
export * from "./constants"
export * from "./delay"
export * from "./tidal"
export * from "./events"
export * from "./fading"
export * from "./fft"
export * from "./functions"
export * from "./fractions"
export * from "./fragmentor"
export * from "./glide"
export * from "./graph"
export * from "./grooves"
export * from "./lfo"
export * from "./mixing"
export * from "./midi-keys"
export * from "./noise"
export * from "./notes"
export * from "./osc"
export * from "./ppqn"
export * from "./smpte"
export * from "./ramp"
export * from "./resampler"
export * from "./sample-rate-converter"
export * from "./time-domain-convolver"
export * from "./frequency-domain-convolver"
export * from "./convolver"
export * from "./rms"
export * from "./simple-limiter"
export * from "./smooth"
export * from "./tempo"
export * from "./time-base"
export * from "./transient-detection"
export * from "./transient-protocol"
export * from "./stereo"
export * from "./rates"
export * from "./utils"
export * from "./value"
export * from "./window"
export * from "./classic-waveform"
export {ConstantTempoMap} from "./ConstantTempoMap"